project:
  type: website
  output-dir: docs

website:
  title: "Diogo Vieri Bolzan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projetos.qmd

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual



